### ISSUE TITLE
Using aliases other than `artisan`

### ISSUE THREAD

**Issue by claytonrcarter** [adriaanzon/fish-artisan-completion#3]
Do you have suggestions for supporting aliases other than `artisan`? I usually use `pa` as an alias for `php artisan`. I've tinkered with this a little bit, but haven't had any luck. I tried altering the lines:

```sh
complete -c artisan -f -n 'test -f artisan; and __fish_use_subcommand' -a '(__fish_artisan_commands_with_descriptions)'
complete -c artisan -f -n 'test -f artisan; and __fish_seen_subcommand_from help' -a '(__fish_artisan_commands)'
```

to be:
```sh
complete -c pa -f -n 'test -f artisan; and __fish_use_subcommand' -a '(__fish_artisan_commands_with_descriptions)'
complete -c pa -f -n 'test -f artisan; and __fish_seen_subcommand_from help' -a '(__fish_artisan_commands)'
```

After reloading my shell, this didn't seem to do anything. Am I missing something obvious? Thanks!

**Comment by adriaanzon** [comment]
If you alter the lines like you described, you should also rename `artisan.fish` to `pa.fish`.

That said, the correct way to configure extra completions is to add this to your `~/.config/fish/config.fish` or `~/.config/fish/completions/pa.fish`:

```fish
complete -c pa -w artisan
```

The latest (unreleased) version of fish will do this automatically for aliases, as the [changelog][1] mentions: 

> Wrapping completions (from `complete -w` or `function -w`) can now inject arguments. For example, `complete gco -w 'git checkout'` now works properly (\#1976). The `alias` function has been updated to respect this behavior.

[1]: https://github.com/fish-shell/fish-shell/blob/master/CHANGELOG.md

**Comment by adriaanzon** [comment]
Good question though, I will add it to the readme.

I hadn't thought of it, since I use an abbreviation that expands `art` to `artisan`.

**Comment by claytonrcarter** [comment]
Awesome, thank you. I couldn't get it to work by editting my `config.fish`, but I did get it working by creating a file `~/.config/fish/completions/pa.fish` that only contains the line `complete -c pa -w artisan`.  Simple and easy; thanks again!
